In [1]:
import numpy as np

In [7]:
array = np.arange(10)
array, array.dtype

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'))

In [6]:
array = np.array( range(10) )
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array = np.arange(10,dtype=np.int16)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [11]:
array = np.arange(10)
array = array.reshape((5,2))
print(array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
array = np.arange(10)
array = array.reshape((2,5))
print(array, array.ndim)

[[0 1 2 3 4]
 [5 6 7 8 9]] 2


In [14]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
array = np.array([20, 310, 30, 100, 410, 302])
array

array([ 20, 310,  30, 100, 410, 302])

In [17]:
array.max(), array.min()

(np.int64(410), np.int64(20))

In [18]:
array.mean()

np.float64(195.33333333333334)

In [19]:
array.ndim

1

In [22]:
array.size

10

In [23]:
array = np.array([20, 310, 30, 100, 410, 302])

array[1] 

np.int64(310)

In [24]:
array = np.array([20, 310, 30, 100, 410, 302])

array[1:4] 

array([310,  30, 100])

In [25]:
array = np.array([20, 310, 30, 100, 410, 302])
array[ array > 100 ]


array([310, 410, 302])

In [26]:
array = np.array([20, 310, 30, 100, 410, 302])
array > 100

array([False,  True, False, False,  True,  True])

In [27]:
array = np.array([20, 310, 30, 100, 410, 302])
conditie = array > 100

array[conditie]



array([310, 410, 302])

In [29]:
array = np.array([20, 310, 30, 100, 410, 302])
conditie1 = array > 100
conditie2 = array < 400

array[ conditie1 & conditie2]

array([310, 302])

In [32]:
array = np.array([20, 310, 30, 100, 410, 302])


# & - si logic
array[ (array > 100) & (array < 400)]

array([310, 302])

In [33]:
array = np.array([20, 310, 30, 100, 410, 302])
# | - si logic
array[ (array < 100) | (array > 400)]


array([ 20,  30, 410])

In [34]:
True or False

True

In [35]:
True and False

False

In [37]:
not True

False